version: "3.8"
services :
  game:
    image : dots-box:1.0
    environment:
      databaseURL: ${DB}
      APIKEY: ${APIKEY}
      AUTH: ${AUTH}
      storageBucket: ${STORE}
    ports: 
      - 5050:5000